### ISSUE TITLE
Create a friendlier development workflow

### ISSUE THREAD

**Issue by Valve** [iron/iron#177]
Currently it's not possible to develop an application with Iron, following the 'change-refresh-test` paradigm. This approach is very convenient and is used in many modern web frameworks.
With interpreted languages this paradigm is natural, scripts are re-parsed and re-executed for every browser request. With compiled languages it's possible if the compilation is fast enough.

Rust compiler is fairly fast, so I would think of a Cargo extension that watches file changes in the background and recompiles them when they occur.
A typical command could be:

`cargo live` - performs initial compilation and starts watching the files. When some of the rust files change, the background recompilation is triggered and then the application is restarted.

Currently one needs to:
1. Kill running application (if it's running).
1. Compile the application with `cargo build`
2. Copy the executable to the place, where the mounted middleware paths make sense.
3. Start the application.

Step 2 is necessary because executable is places in `target` directory, where paths like `assets/main.js` or `views/index.html` don't exist.

**Comment by cyplo** [comment]
Hi ! Just found this issue, do you know if there is a good way to do this nowadays ? Thanks !

**Comment by mathroc** [comment]
there is ongoing work that could solve this here : passcod/cargo-watch#25

**Comment by Hoverbear** [comment]
Closing since this seems to be resolved by other libraries/repos. Thanks everyone! :)
