### ISSUE TITLE
response streaming?

### ISSUE THREAD

**Issue by jaredly** [iron/iron#225]
Is there a way to stream an IronResponse?

**Comment by reem** [comment]
Closing since there's not a huge action item for us here. Feel free to comment if you think there's more to say here.

**Comment by azasypkin** [comment]
Hey @reem, is there any example of how "assign a Reader to body"?

I have something very similar to https://github.com/iron/iron/issues/423, but I want to continuously stream response returned by Hyper client.

Thanks!

**Comment by azasypkin** [comment]
Thanks for your reply @untitaker! So as the result I've just created custom ```struct``` that implements ```WriteBody + Send```. If simplify a lot and omit error handling ```write_body``` will look like in case someone finds it useful:
```rust
fn write_body(&mut self, response_body: &mut ResponseBody) -> io::Result<()> {
    let client = hyper::Client::new();
    
    let mut streamed_response = client.get(&self.mjpeg_stream_url)
        .header(Connection::keep_alive())
        .send()
        .unwrap();

    let mut buffer: [u8;300] = [0;300];

    loop {
        streamed_response.read_exact(&mut buffer).unwrap();
        response_body.write(&buffer).unwrap();
        response_body.flush().unwrap();
    }

    Ok(())
}
```

**Comment by untitaker** [comment]
As far as I can tell you can just use [std::io::copy](https://doc.rust-lang.org/std/io/fn.copy.html) for this?
