### ISSUE TITLE
Put middleware on crates.io

### ISSUE THREAD

**Issue by ProtectedMode** [iron/iron#232]
Currently, I get the following build error when trying to build with the session middleware:
```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.0.1 (https://github.com/sfackler/rust-openssl.git#b084ddc7)
  openssl2-sys v1.0.0
```
As far as I know, this is because Iron uses OpenSSL from crates.io, while the session middleware still uses the OpenSSL library from Github. 

Whether this issue is caused by the middleware not being on crates.io, is still irrelevant to the fact that it be better if everything could be found on crates.io.

**Comment by reem** [comment]
Fixed a while back.
