### ISSUE TITLE
Allow several handlers

### ISSUE THREAD

**Issue by s-panferov** [iron/iron#239]
Hello @reem. It's cool that you moved Iron to Hyper. So I am happy to say that I am moving [rustless](https://github.com/rustless/rustless) to Iron.

During the process of porting I found several things that disappoint me a little bit. The first one is support of only one `Handler` for application. I came from Ruby world and I saw a lot of projects that use both Rails and Sinatra/Grape. Rails serves regular HTTP-requests for HTML pages and Grape/Sinatra provides an API.

So I think that we need to extend the current implementation of `Chain`. Maybe you would want to look at [this](https://github.com/rustless/rustless/blob/master/src/middleware.rs) implementation. There is a special error (`NotMatchError `) to say that the handler didn't match and we can go to the next.

Maybe we can just add an another instance that will iterate through `Handlers` and implement `Handler` itself. What do you think about it?

**Comment by reem** [comment]
Closing, unless you have a further action item.
