### ISSUE TITLE
Error handling shows wrong port

### ISSUE THREAD

**Issue by graue** [iron/iron#245]
I've got a server running on localhost:3000, yet going to a URL that doesn't have a route defined shows:

```
ERROR:iron::iron: Error handling:
Request {
    url: http://localhost:80/goodbye
    method: GET
    remote_addr: 127.0.0.1:48341
    body: []
}
Error was: (HTTP/1.1 500 Internal Server Error Internal Server Error

, Err(NoRoute))
```

Note port 80 in the URL.

As a guess, perhaps something isn't passing the port along, so `from_generic_url` is defaulting to 80.

**Comment by michaelsproul** [comment]
Sorry it took so long to get a fix for this!

Thanks for reporting!
