### ISSUE TITLE
error: unresolved import `error::ErrorRefExt`. There is no `ErrorRefExt` in `error` at build

### ISSUE THREAD

**Issue by khades** [iron/iron#246]
Using latest rust for x64 linux.

   Compiling iron v0.0.8 (https://github.com/iron/iron.git#a82c75c2)
     Running `rustc src/lib.rs --crate-name iron --crate-type lib -g -C metadata=7dae21dfa93b73d6 -C extra-filename=-7dae21dfa93b73d6 --out-dir /home/khades/test-project-rust/target/deps --dep-info /home/khades/test-project-rust/target/.fingerprint/iron-7dae21dfa93b73d6/dep-lib-iron -L /home/khades/test-project-rust/target/deps -L /home/khades/test-project-rust/target/deps --extern url=/home/khades/test-project-rust/target/deps/liburl-591bb8aaf60230c2.rlib --extern typemap=/home/khades/test-project-rust/target/deps/libtypemap-4aafc0643ed658ee.rlib --extern error=/home/khades/test-project-rust/target/deps/liberror-14128451581aeed2.rlib --extern plugin=/home/khades/test-project-rust/target/deps/libplugin-c932a4ffd97a9fec.rlib --extern hyper=/home/khades/test-project-rust/target/deps/libhyper-23525b4fcc2807b4.rlib --extern modifier=/home/khades/test-project-rust/target/deps/libmodifier-8f717f295033a0e7.rlib -Awarnings -L /usr/lib/x86_64-linux-gnu -L /home/khades/test-project-rust/target/build/time-ebf8a3b3c11a2cc2/out`
src/lib.rs:62:24: 62:35 error: unresolved import `error::ErrorRefExt`. There is no `ErrorRefExt` in `error`
src/lib.rs:62 pub use error::{Error, ErrorRefExt};
                                     ^~~~~~~~~~~
src/lib.rs:86:27: 86:38 error: unresolved import (maybe you meant `ErrorRefExt::*`?)
src/lib.rs:86     pub use {Set, Plugin, ErrorRefExt, Chain, Request,
                                        ^~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `iron`.
 
Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name iron --crate-type lib -g -C metadata=7dae21dfa93b73d6 -C extra-filename=-7dae21dfa93b73d6 --out-dir /home/khades/test-project-rust/target/deps --dep-info /home/khades/test-project-rust/target/.fingerprint/iron-7dae21dfa93b73d6/dep-lib-iron -L /home/khades/test-project-rust/target/deps -L /home/khades/test-project-rust/target/deps --extern url=/home/khades/test-project-rust/target/deps/liburl-591bb8aaf60230c2.rlib --extern typemap=/home/khades/test-project-rust/target/deps/libtypemap-4aafc0643ed658ee.rlib --extern error=/home/khades/test-project-rust/target/deps/liberror-14128451581aeed2.rlib --extern plugin=/home/khades/test-project-rust/target/deps/libplugin-c932a4ffd97a9fec.rlib --extern hyper=/home/khades/test-project-rust/target/deps/libhyper-23525b4fcc2807b4.rlib --extern modifier=/home/khades/test-project-rust/target/deps/libmodifier-8f717f295033a0e7.rlib -Awarnings -L /usr/lib/x86_64-linux-gnu -L /home/khades/test-project-rust/target/build/time-ebf8a3b3c11a2cc2/out` (status=101)

**Comment by reem** [comment]
This was fixed a while back, so closing.
