### ISSUE TITLE
multiple matching crates for `log`

### ISSUE THREAD

**Issue by leonbohn** [iron/iron#250]
When trying to compile a small example with iron 0.0.9 I get the following errors.

    warning: using multiple versions of crate `regex`
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:136:1: 136:21 note: used here
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:136 extern crate mucell;
                                                                                              ^~~~~~~~~~~~~~~~~~~~
    note: crate name: regex
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:132:23: 132:40 note: used here
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:132 #[phase(plugin,link)] extern crate log;
                                                                                                                    ^~~~~~~~~~~~~~~~~
    note: crate name: regex
    warning: using multiple versions of crate `log`
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:136:1: 136:21 note: used here
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:136 extern crate mucell;
                                                                                              ^~~~~~~~~~~~~~~~~~~~
    note: crate name: log
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:132:23: 132:40 note: used here
    C:\Users\leon\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.0.17\src\lib.rs:132 #[phase(plugin,link)] extern crate log;
                                                                                                                    ^~~~~~~~~~~~~~~~~
    note: crate name: log
       Compiling iron v0.0.9
    src\lib.rs:25:24: 25:41 error: multiple matching crates for `log`
    src\lib.rs:25 #[phase(plugin, link)] extern crate log;
                                         ^~~~~~~~~~~~~~~~~
    note: candidates:
    note: path: C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\log-4e7c5e5c.dll
    note: path: C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\liblog-4e7c5e5c.rlib
    note: crate name: log
    note: path: C:\Users\leon\iron_test\target\deps\liblog-b6110bc38225692d.rlib
    note: crate name: log
    src\lib.rs:25:24: 25:41 error: can't find crate for `log`
    src\lib.rs:25 #[phase(plugin, link)] extern crate log;
                                         ^~~~~~~~~~~~~~~~~
    error: aborting due to 2 previous errors
    Could not compile `iron`.

    To learn more, run the command again with --verbose.

Although I really do not have a clue about how to resolve them, I just wanted to let you know ^^

This happens on Windows with rustc 0.13.0-nightly (96a3c7c6a 2014-12-23 22:21:10 +0000) and nothing apart from
    [dependencies]
    iron = "*"
in my cargo.toml.

**Comment by pzol** [comment]
This works in 0.0.11
