### ISSUE TITLE
Build failure on the the latest rust-nightly build

### ISSUE THREAD

**Issue by blacksoil** [iron/iron#255]
aharijanto@aharijanto-ThinkPad-X201:~/Programming/iron$ cargo build
   Compiling regex v0.1.6
   Compiling pkg-config v0.1.3
   Compiling modifier v0.0.5
   Compiling phantom v0.0.2
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:23:57: 23:61 error: the trait `core::kinds::Sized` is not implemented for the type `Self`
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:23     fn set<M: Modifier<Self>>(mut self, modifier: M) -> Self {
                                                                                                                                                      ^~~~
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:23:31: 23:34 error: the trait `core::kinds::Sized` is not implemented for the type `Self`
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:23     fn set<M: Modifier<Self>>(mut self, modifier: M) -> Self {
                                                                                                                            ^~~
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:31:18: 31:30 error: the trait `core::kinds::Sized` is not implemented for the type `Self`
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.5/src/lib.rs:31         modifier.modify(self);
                                                                                                               ^~~~~~~~~~~~
error: aborting due to 3 previous errors
   Compiling typeable v0.0.4
   Compiling gcc v0.1.3
   Compiling rustc-serialize v0.2.2
   Compiling mucell v0.1.6
   Compiling unsafe-any v0.2.0
Build failed, waiting for other jobs to finish...

**Comment by blacksoil** [comment]
There's another issue when compiling "error" crate:

cargo build
   Compiling error v0.0.3 (file:///home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3)
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:10:16: 10:19 warning: deprecated syntax; use the `self` keyword now
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:10 use std::fmt::{mod, Show, Formatter};
                                                                                                          ^~~
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:4:12: 4:28 warning: feature is deprecated and will only be available for a limited time, please rewrite code that relies on it
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:4 #![feature(old_orphan_check)]
                                                                                                     ^~~~~~~~~~~~~~~~
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:4:12: 4:28 warning: feature is deprecated and will only be available for a limited time, please rewrite code that relies on it
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:4 #![feature(old_orphan_check)]
                                                                                                     ^~~~~~~~~~~~~~~~
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:84:1: 86:2 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `core::fmt::Show` for the type `Error + 'static`
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:84 impl Show for Error {
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:85     fn fmt(&self, f: &mut Formatter) -> fmt::Result { (*self).fmt(f) }
/home/aharijanto/.cargo/registry/src/github.com-1ecc6299db9ec823/error-0.0.3/src/lib.rs:86 }
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123


Could not compile `error`.

**Comment by danielbeutel** [comment]
Also failing on 1.0.0-alpha. Any plans to support alpha (and later beta/stable)?

**Comment by reem** [comment]
Iron will continue to track nightly (like the rest of the ecosystem) until
1.0 stable, when it will split to have two branches, one for 1.0 stable and
one for 1.0 nightlies. This will continue into 1.X versions.

Eventually Iron itself will hit 1.0 and adopt a similar versioning scheme
to Rust itself, but that's a while off.

**Comment by sunng87** [comment]
Refer this ICE that blocks iron build: rust-lang/rust#20676

**Comment by reem** [comment]
Fixed.
