### ISSUE TITLE
Implement `Handler` for `Fn(Mut) + Send + Sync`

### ISSUE THREAD

**Issue by cybergeek94** [iron/iron#267]
Unboxed closures are here to stay, and mostly stable now. I don't think there are any issues with this.

**Comment by reem** [comment]
This appears to already be done: https://github.com/iron/iron/blob/master/src/middleware.rs#L279

Is there something else that this doesn't cover?

**Comment by cybergeek94** [comment]
Ah. [The docs just need rebuilt then.][1] :smile: 

[1]: http://ironframework.io/doc/iron/middleware/trait.Handler.html
