### ISSUE TITLE
Add core middleware to rust-ci

### ISSUE THREAD

**Issue by ProtectedMode** [iron/iron#271]
It would be easier to spot broken middleware (and possibly fix them) if rust-ci was enabled for the core middleware.

**Comment by untitaker** [comment]
I think we rather need something like greenkeeper for Rust.

**Comment by reem** [comment]
@untitaker rust-ci is similar to greenkeeper, it triggers a nightly rebuild on travis, so you know every day if something has caused your build to fail.

**Comment by Hoverbear** [comment]
Rust-ci doesn't exist anymore, closing this.
