### ISSUE TITLE
Examples have unreachable printlns

### ISSUE THREAD

**Issue by reem** [iron/iron#277]
Due to the new join guard structure, these printlns are no longer reachable.

**Comment by davidrhyswhite** [comment]
Thought I'd give this a go since I'm fairly new to both Rust and Iron and it's marked as easy. Ignore the first commit, I didn't read the contributing doc first. ;)

**Comment by reem** [comment]
Awesome! Feel free to make a PR and I'll give you a review of the changes.

**Comment by reem** [comment]
Fixed!
