### ISSUE TITLE
Question..

### ISSUE THREAD

**Issue by dariusc93** [iron/iron#281]
Though this is not much of an issue but a question. I been looking at iron for awhile and was wondering how stable is iron to be used in production? Is it able to compete against something in another language like vibe.d when it comes to performance? I know rust itself is still in development so performance can change but are there any benchmarks to compare the performance between iron and vibe.d + libevent and vibe.d + libasync (native event driver)?

**Comment by reem** [comment]
Iron and rust are still pretty unstable, so I wouldn't recommend using them in production just yet. There are also a bunch of polish issues with Iron and associated middleware, though I am rapidly addressing them and making it a core focus for the next few weeks.

Performance is definitely a goal of Iron, but it has to be framed inside the blocking-IO world that it lives in, which means it won't be as fast as some other fast solutions built on asynchronous IO. That said, Iron wrecks node.js and other higher-level evented libraries in req/sec (by like an order of magnitude). 

I don't know enough about vibe.d (I had to google it) to really compare it to Iron, but from what I've read it appears to be based on non-blocking IO, which means it will have a different performance model than what Iron has.

**Comment by reem** [comment]
Since this is just a question, I'm closing.
