### ISSUE TITLE
Implement BodyReader plugin

### ISSUE THREAD

**Issue by s-panferov** [iron/iron#287]
@reem Hello! You have landed #266 (:+1:) and now we need to introduce some standardized way to deal with `Body` in middlewares and handlers. I say `standardized` because I want to support interoperability between internal and external middlewares.

I propose:

1. Implement `BodyReader` plugin. It must be smart enough to allow to specify max length that it can read.  
2. Mention `BodyReader` in doc as a default way to deal with all kinds of bodies except of `multipart/form-data`.

What do you think?

**Comment by reem** [comment]
Seems like this belongs in a proper iron/body-parser implementation.

**Comment by s-panferov** [comment]
It can be a middleware, it's not a problem. And I think that it is common enough to be right in the core. If you agreed with me I'll implement this (or I can rewrite the body-parser).

**Comment by reem** [comment]
Given that body-access is the poster-child for plugins, it seems like it should be one. I'd rather a patch to body-parser for now, and we can maybe move it to core in the future.

**Comment by s-panferov** [comment]
See https://github.com/iron/body-parser/pull/43
