### ISSUE TITLE
Become slow?

### ISSUE THREAD

**Issue by nyrf** [iron/iron#292]
I run `wrk -t12 -c900 -d10s http://127.0.0.1:3000/`, got 
```
Running 10s test @ http://127.0.0.1:3000
  12 threads and 900 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.08ms    3.48ms  11.37ms   86.91%
    Req/Sec     1.09k    65.57     1.30k    87.60%
  42240 requests in 10.04s, 4.59MB read
  Socket errors: connect 0, read 0, write 0, timeout 3558
Requests/sec:   4206.42
Transfer/sec:    468.29KB
```
A half month ago, i got almost 80k reqs/sec.

**Comment by reem** [comment]
Did you compile with optimizations?

**Comment by reem** [comment]
I just tested and got 92k locally.

**Comment by nyrf** [comment]
I have tried on my md101 8g ram and on ubuntu 14.10, got same result.

**Comment by reem** [comment]
Can I get the exact commands you used to compile iron, run the example, and run the benchmark?

**Comment by nyrf** [comment]
This is my cargo.toml

```toml
[package]

name = "demo"
version = "0.0.1"
authors = ["nyrf <nyrf1125@gmail.com>"]

[dependencies]
iron="*"
```

`src/main.rs`

```rust
extern crate iron;

use iron::prelude::*;
use iron::status;

fn main() {
    Iron::new(|&: _: &mut Request| {
        Ok(Response::with((status::Ok, "Hello world!")))
    }).listen("localhost:3000").unwrap();
}
```

Then `cargo build`, `cargo run`

**Comment by reem** [comment]
You are building without optimizations. Use `cargo build --release`, `cargo run --release`.

**Comment by nyrf** [comment]
Oh, i see, thank you. the new ruslt.

```
Running 10s test @ http://localhost:3000/
  12 threads and 900 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.17ms    6.15ms  22.09ms   91.29%
    Req/Sec    22.41k     8.06k   42.78k    68.87%
  206459 requests in 10.07s, 22.45MB read
  Socket errors: connect 0, read 855, write 5, timeout 2942
Requests/sec:  20494.03
Transfer/sec:      2.23MB
```

**Comment by reem** [comment]
Are you running on a VM? VMs are usually slower.

**Comment by nyrf** [comment]
No, i use my md101 , 8Gram  and samsung SSD 840PRO 256G.

**Comment by reem** [comment]
I'm not sure what to tell you, a lot of things can influence these numbers. For instance, when my computer's battery is low I get like 500 req/s.

Unfortunately, I can't really fix this right now without being able to at least reproduce locally, sorry.

The best thing you could do would be to maybe profile the executable while it is being benchmarked a few times and include that, along with commands and computer specs.

If you get back to me with that I might be able to re-open the issue and fix it, if the profiling is informative.
