### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by dbalchev** [iron/iron#305]
The documentation at http://ironframework.io is a bit outdated. 
E.g. `iron::Iron` has method `listen` and not methods `http` or `https`. http://ironframework.io/doc/iron/struct.Iron.html

**Comment by reem** [comment]
This is a known issue, but @zzmp is on it!

**Comment by dbalchev** [comment]
That was fast feedback.
Thanks!

**Comment by reem** [comment]
Boom, updated!
