### ISSUE TITLE
Better Documentation for "relative" Urls

### ISSUE THREAD

**Issue by golddranks** [iron/iron#309]
In iron/src/request/url.rs, it says about Url::parse(input: &str) that "The input must be a valid URL in a relative scheme for this to succeed."

However, valid relative URLs cause a panic. The upstream repo, rust-url docstring says: "In particular, relative URL references are parse errors since no base URL is provided."

So there's a mismatch there. Is the documentation here wrong, or has the upstream API changed...?

**Comment by reem** [comment]
I think the documentation here is not wrong, just highly technical and possibly in-need of rephrasing. 

A `valid URL in a relative scheme` is not the same as a `valid relative URL`; in this case "scheme" refers to the protocol, e.g. http, https, not the format of the url itself.

**Comment by golddranks** [comment]
Ah, I see. So does `a relative scheme` mean a URL without specifying the scheme, then? Like "//google.com"? In that case the docstring could indeed use some rephrasing to be more clear.

**Comment by michaelsproul** [comment]
Sorry, this was me! This documentation is referring to the definition in the URL spec:

https://url.spec.whatwg.org/#relative-scheme

I think that adding a comment about how a relative scheme is distinct from a relative URL, and linking to the spec would be one solution.

**Comment by diogovk** [comment]
The url https://url.spec.whatwg.org/#relative-scheme seems to be no longer working.
Was relative-scheme renamed to scheme in the specification?
https://url.spec.whatwg.org/#concept-url-scheme
What's the diference between scheme and relative-scheme?
