### ISSUE TITLE
Build Error: wrong number of lifetime parameters

### ISSUE THREAD

**Issue by ccostes** [iron/iron#313]
Trying to build the current version and getting this error in request/mod.rs  Any ideas?

~~~
error: wrong number of lifetime parameters: expected 2, found 1 [E0107]
/home/chris/.cargo/git/checkouts/iron-2865eca1baef072c/master/src/request/mod.rs:67     
pub fn from_http(req: HttpRequest<'a>, local_addr: SocketAddr, protocol: &Protocol)
                     ^~~~~~~~~~~~~~~
~~~

**Comment by reem** [comment]
I'm working on a fix for this right now. #314 is the start but I have to fix mocking tools too.

**Comment by ccostes** [comment]
Awesome, thanks for fixing this so quickly! This project looks pretty cool and I'm excited to check it out.
