### ISSUE TITLE
Iron::{http, https} docs should explicitly mention the guard

### ISSUE THREAD

**Issue by reem** [iron/iron#319]
The exact blocking behavior is not well documented.

**Comment by gsquire** [comment]
Are you referring to the join guard returned in a `thread::scoped` function? It says that it ["blocks until it terminates"](https://doc.rust-lang.org/std/thread/#scoped-threads) and looking at the Hyper source I see the listener [creates](https://github.com/hyperium/hyper/blob/4c5a42bcdab18f59d0d3ee3512d1e33c4dada2f2/src/server/mod.rs#L107) a scoped thread when making the connection pool.

If this is what you are referring to, then I will gladly take a shot at updating the documentation.

**Comment by reem** [comment]
Yup.

**Comment by reem** [comment]
@gsquire thanks for fixing :)
