### ISSUE TITLE
iron should have specified version of dependencies in Cargo.toml

### ISSUE THREAD

**Issue by jarod** [iron/iron#321]
With the latest release 0.1.13, it built on travis( https://travis-ci.org/iron/iron/builds/55321591). But I can't reproduce the build result with rust nightly 2015-03-23 because conduit-mime-types updated to 0.7.3. but the travis build is with conduit-mime-types 0.7.2

```
$ rustc --version
rustc 1.0.0-nightly (b0aad7dd4 2015-03-22) (built 2015-03-23)
conduit-mime-types-0.7.3/src/lib.rs:3:1: 3:30 error: can't find crate for `rustc_serialize`
conduit-mime-types-0.7.3/src/lib.rs:3 extern crate rustc_serialize;
```

**Comment by reem** [comment]
The build is fixed on master. I'm closing because I don't want to do this until there is some ecosystem stability because it makes the developer workflow really hard (have to release and do menial updates even more often).
