### ISSUE TITLE
Bad request when no host is specified

### ISSUE THREAD

**Issue by gsingh93** [iron/iron#327]
I'm dealing with an HTTP client that is sending a request with no `Host` header and so I'm getting [this error](https://github.com/iron/iron/blob/fd5ccecc4ed7d5a79bcf8654848f51ce188756a8/src/request/mod.rs#L88):
```
ERROR:iron::iron: Error creating request:
    No host specified in request
```
The comment in the code says it's only required for HTTP/1.1, but this particular client is using HTTP/1.0. Would it be possible to do a version check here and only fail here if there is no host and the version is HTTP/1.1?

This may seem like a strange case, but this is for an application that isn't a website/web server but still uses the HTTP protocol. Using `hyper` directly might be a better fit, but this still seems like it could be fixed here.

**Comment by reem** [comment]
I think this current case is mostly for implementation concerns - due to the nature of `rust-url` we need a full url including host to create the request's url instance. I'll see what I can do about fixing this though, since there's no need to be unnecessarily mean to HTTP/1.0 :).

**Comment by Hoverbear** [comment]
You can reproduce this by running `cargo run --examples hello` and in another terminal issuins this curl command:

```bash
curl --dump-header - -0 -H 'Host:' localhost:3000
```

Output:

```bash
$ curl localhost:3000
Hello world!%
$ curl --dump-header - -0 -H 'Host:' localhost:3000
HTTP/1.0 400 Bad Request
Date: Sat, 01 Oct 2016 07:30:45 GMT
Connection: close
Transfer-Encoding: chunked
```
