### ISSUE TITLE
Docs don't show `Modifier` trait anywhere

### ISSUE THREAD

**Issue by huonw** [iron/iron#338]
E.g. http://ironframework.io/doc/iron/response/struct.Response.html has `fn with<M: Modifier<Response>>(m: M) -> Response`, but the `Modifier` trait isn't a link, and the search doesn't find it either. Being able to see the trait is useful to see what (in this case) `with` can be used for.

**Comment by reem** [comment]
@zzmp this is what I was talking about

**Comment by zzmp** [comment]
I've updated the build scripts to include all dependencies.
Check it out at github.com/iron-bot/build-doc

Unfortunately, it didn't seem like Cargo could handle doccing multiple crates, so I rewrite the search index as it docs.
