### ISSUE TITLE
contribute a todobackend example implementation using Iron

### ISSUE THREAD

**Issue by moredip** [iron/iron#343]
Any chance I could persuade you to build a todobackend implementation using Iron? It's a pretty simple process and the end result would provide a nice reference implementation for people new to Iron. You'd also gain a little bit of free marketing by having the implementation listed up on todobackend.com.

I'm happy to help if you have any questions while building out the implementation.

**Comment by fsommar** [comment]
I started an implementation [here](https://github.com/fsommar/todo-iron) with an in-memory list to maintain all todos. Currently it only supports adding a todo, getting all todos and deleting all todos.

**Comment by fsommar** [comment]
It's working fully now, but I wouldn't say the code is idiomatic of Iron and Rust because of the lack of error handling.

**Comment by Hoverbear** [comment]
Big props to @fsommar to taking this on and exploring! If you're interested in helping with their implementation please go do so on that repository.

Closing this for now.
