### ISSUE TITLE
Chain#link should return the chain

### ISSUE THREAD

**Issue by singpolyma** [iron/iron#353]
This would allow for nice chaining syntax:

    Chain::new(handler).link(thing1).link(thing2)

**Comment by AndrewBrinker** [comment]
Presumably, if `Chain.link()` is being updated, we should also update `link_before()`, `link_after()`, and `around()`, yes?

(As an aside, should `around()` be renamed to `link_around()` for consistency's sake?)

**Comment by reem** [comment]
@AndrewBrinker yes and yes.

I am in favor of this change.

**Comment by AndrewBrinker** [comment]
Cool. I am working on it now.

**Comment by sbstp** [comment]
I think this should be closed.

**Comment by PlasmaPower** [comment]
This has been fixed, I'd like to reiterate the request for this issue to be closed.
