### ISSUE TITLE
Per-thread resources

### ISSUE THREAD

**Issue by singpolyma** [iron/iron#354]
Is there a good way to create resources that cannot be shared between threads on a per-thread instead of a per-request basis with iron?

**Comment by reem** [comment]
Each request is handled in a different thread, so the request extensions can act as a form of thread-local storage.

**Comment by singpolyma** [comment]
Hmm, if it's one-thread-per-request then I guess this request doesn't make much sense :)  Should have looked closer before assuming there was a pool or something.

**Comment by reem** [comment]
@singpolyma there is a pool, but a request gets exclusive access to the thread it's being handled in until it is finished, then another request can be handled on the same thread.

**Comment by singpolyma** [comment]
@reem oh, hmm, so the idea is if I put a mutable reference in a plugin, I could maybe share that way?
