### ISSUE TITLE
Combine router and content-type examples?

### ISSUE THREAD

**Issue by SamuelMarks** [iron/iron#360]
How do I combine [router](https://github.com/iron/router/blob/master/examples/simple.rs) and [content type](https://github.com/iron/iron/blob/master/examples/content_type.rs)?

Attempts (commented out):
```
extern crate iron;
extern crate router;
//extern crate hyper;

use iron::prelude::*;
use iron::status;

/*use hyper::header::{Headers, ContentType};
use hyper::mime::{Mime, TopLevel, SubLevel, Attr, Value};*/

use router::{Router};

fn main() {
    /*
    let mut headers = Headers::new();
    headers.set( // There's also some `.json()` but couldn't get that to compile
        ContentType(Mime(TopLevel::Application, SubLevel::Json,
                     vec![(Attr::Charset, Value::Utf8)])) 
    );
    let content_type = "application/json".parse::<Mime>().unwrap();
    */

    let mut router = Router::new();
    router.post("/api/foo", move | _req: &mut Request | {
        //Ok(Response::with((content_type, status::Ok, "{}")))
        Ok(Response::with((status::Ok, "{}")))
    });

    let serve_on = "localhost:3000";
    println!("Starting server at {}", serve_on);
    Iron::new(router).http(serve_on).unwrap();
}
```

**Comment by leodasvacas** [comment]
I think you have a closure problem. Why not declare `content_type` inside the handler?

**Comment by SamuelMarks** [comment]
Thanks, that did the trick.

I thought that closures exposed their context?

**Comment by leodasvacas** [comment]
It's an ownership issue, directly related to the difference between the three types of closures: `FnOnce` (only callable once), `FnMut` (mutates the context) and `Fn` (only reads the context). A handler needs to be `Fn`, which gives stronger concurrency guarantees. `move` closures will take ownership of the context, so it's easy for it to become `FnOnce` or `FnMut`. [Huon has a great in-depth post on this](https://huonw.github.io/blog/2015/05/finding-closure-in-rust/).
