### ISSUE TITLE
how to get a hyper request from iron?

### ISSUE THREAD

**Issue by ilkosta** [iron/iron#365]
Hi, I'm new to rust and I would like to use some hyper lib inside iron that accept `hyper::server::Request` or `hyper::header::Headers`, for example [formdata](http://github.com/mikedilger/formdata).

There are some examples I can follow?

**Comment by SkylerLipthay** [comment]
Hi! We actually have a new plugin that encapsulates `formdata` called [`iron/params`](https://github.com/iron/params); you might be interested in using that. Regardless, you can check out how the `hyper::header::Headers` and `formdata::Request` types were integrated [here](https://github.com/iron/params/blob/master/src/lib.rs#L525) and [here](https://github.com/iron/params/blob/master/src/lib.rs#L562).

**Comment by ilkosta** [comment]
really thanks! great work
