### ISSUE TITLE
improve error example

### ISSUE THREAD

**Issue by ilkosta** [iron/iron#368]
Hi, 
Do you think that integrating the `error.rs` and the `around.rs` examples are too confusing?

I think to this because the `error.rs` don't show the [StringError](https://github.com/iron/iron/blob/5d5f9851c3265ecc0bccd0e826230b6643560022/examples/error.rs#L40) handled.

Thanks

**Comment by reem** [comment]
Perhaps there's room for another example which integrates these concepts? More examples is better, IMO.

**Comment by reem** [comment]
cc #311

**Comment by Hoverbear** [comment]
Please feel free to submit a PR adding examples. I'm closing this in favor of #311.
