### ISSUE TITLE
No way to use `addr` field of `Iron` struct?

### ISSUE THREAD

**Issue by cmbrandenburg** [iron/iron#373]
How are we supposed to use the `addr` field of the `Iron` struct in a meaningful way? The field is populated with the server's bound-to address _after_ listening begins, but listening begins by calling the `http`, `https`, or `listen_with` functions—all of which consume the `Iron` instance.

Am I missing something?

**Comment by reem** [comment]
It is used to populate the `local_addr` field of `Request` in `Request::from_http`, and can be "accessed" through that. It is meant to be an implementation detail of the `Iron` type.
