### ISSUE TITLE
Could you compare Iron and Nickel?

### ISSUE THREAD

**Issue by ScottHuangZL** [iron/iron#384]
Could you compare Iron and Nickel?
What is pro and con? 
It will help the new comer to select one of them to suit to their business situation. Thanks.

**Comment by sunng87** [comment]
IMO, Iron has a beautiful architecture. In Iron, the whole application is made up with a few middlewares. That's pretty much like [Clojure's Ring](https://github.com/ring-clojure/ring). In Iron, everything is middleware, you can choose your own composition of middlewares. 

For example, 

* the route middleware dispatches requests to different handlers
* the body reader middleware parses http request body and transform them into data structures easier to deal with
* [my handlebars template](https://github.com/sunng87/handlebars-iron) middleware renders data models into web pages

The middleware architecture splits your code by its functionality, made it easier to test.

Nickel is more like nodejs's express framework, it's an all-in-one framework comparing to Iron. It has most essential components in web development built-in. I have never use nickel, but I used to investigate the possibility for making handlebars template engine work for it, and failed. 

I'm not saying which one is better. To me, Iron is simpler, while Nickel seems easier. And personally I like the Iron design.

**Comment by ScottHuangZL** [comment]
Thanks. Welcome more comments coming.

**Comment by dariusc93** [comment]
what @sunng87 stated pretty much sums it up. I've used both nickel and iron but honestly I do find iron being more "pluggable" in a sense to where you can bring or create your own middleware with ease. I been debating on which to use but havent came to a direct conclusion.

**Comment by Hoverbear** [comment]
Hey folks! I'm closing this issue since it's been inactive for almost a year. Please feel free to contribute some documentation in some way comparing the two, or even writing an article/post about it on your fancy websites. :)
