### ISSUE TITLE
Allow the user to provide a bound TcpListener to the server

### ISSUE THREAD

**Issue by 4xrsJCr9** [iron/iron#386]
This would support the scenario in which a process (running as root) binds a privileged port and then `setuid's` to an unprivileged user.

Current usage leaves a small window (theoretically, at least) between starting the server and calling `setuid` in which requests could be processed as root.

**Comment by reem** [comment]
This would definitely be useful. I've started work towards solving this in the above linked PR to hyper.

**Comment by sfackler** [comment]
This is implemented in #510
