### ISSUE TITLE
Re-export Hyper::server::Listening

### ISSUE THREAD

**Issue by dbrgn** [iron/iron#406]
Is there a re-export for `Hyper::Server::Listening` somewhere (the object returned by `Iron::http`)? Or do I have to add hyper as an explicit dependency, just because I want to be able to stop a server I started?

If not, it would be nice if you could add the re-export :) In my opinion all the API of Iron should be importable from Iron :)

**Comment by rnestler** [comment]
https://github.com/iron/iron/blob/1c37acbf3cacc2f0da91c0123bb4bfd6bf56809b/src/iron.rs#L9
Looks like a public export of `hyper::server::Listening`
