### ISSUE TITLE
Dependency issue with Hyper

### ISSUE THREAD

**Issue by ShaunGillies** [iron/iron#407]
Iron keeps compiling using Hyper v0.6.16, which ultimately results in undefined reference errors on Debian testing machines, as the OS no longer supports SSLv3. Is there an expected update which will allow Iron to use Hyper v0.7.0?

**Comment by reem** [comment]
Yes, I will attempt to do a release in the coming days bumping the version of hyper used to the 0.7 series, which should resolve this issue.

**Comment by ShaunGillies** [comment]
Alright, awesome. Thanks!

**Comment by reem** [comment]
0.2.5 with hyper 0.7 released!
