### ISSUE TITLE
Change SSL to opt-in

### ISSUE THREAD

**Issue by mvdnes** [iron/iron#409]
Currently the SSL library is opt-out, having to manually specify `default-features=false` in every crate that depends on Iron.

Many of the middleware available does not care about whether SSL is enabled or not. However, many libraries do not opt out of the feature, making compilation without it almost impossible. This is especially an issue on Windows where compiling openssl-sys is not easy.

#351 did not take a clear stand on inclusion of this feature. I would like to see this changed to the opt-in behaviour.

Sample middleware which are currently unsusable without ssl:
* [handlebars-iron](https://github.com/sunng87/handlebars-iron/blob/master/Cargo.toml)
* [router](https://github.com/iron/router) (present in TOML, but not yet pushed to crates.io)
* [mount](https://github.com/iron/mount/blob/master/Cargo.toml)
* [staticfile](https://github.com/iron/staticfile/blob/master/Cargo.toml)

**Comment by untitaker** [comment]
Perhaps this is the way to go, yes. @reem?

**Comment by reem** [comment]
Yes, I agree making ssl opt-in is the right move here.

**Comment by mvdnes** [comment]
Great! This will greatly improve the experience on Windows. Should I submit a PR removing the default or is there more work to be done?

**Comment by untitaker** [comment]
I don't think there's any other change required.

Reverting all those `default-features = false` PRs is not required to make this work, although I suppose it should be done at some point.

**Comment by reem** [comment]
Remove the default feature should be all that is needed.
