### ISSUE TITLE
failed to run custom build command for `openssl v0.7.5`

### ISSUE THREAD

**Issue by wubin1989** [iron/iron#420]
my openssl version is 1.0.2.d-1, not 0.7.5
when will iron support 1.0.2.d-1?

**Comment by reem** [comment]
@wubin1989 openssl v0.7.5 is referring to version 0.7.5 of rust-openssl, see https://github.com/sfackler/rust-openssl not the version of openssl itself.

**Comment by Hoverbear** [comment]
This is a question and has been answered, thus it is closed.
