### ISSUE TITLE
Is it possible render template?

### ISSUE THREAD

**Issue by shinriyo** [iron/iron#430]
Hi there.
I used the iron framework.
I read  `template rendering` in the README.
There are how to render only string.
but, I didn't find how to render "index.html"
```
    let mut router = Router::new();
    router.get("/", move |r: &mut Request| hello_world(r));

    fn hello_world(_: &mut Request) -> IronResult<Response> {
        // do something.

        Ok(Response::with(status::Ok))
    }
```

**Comment by sunng87** [comment]
Template rendering is done via middleware. Take a look at handlebars-iron and its example:
https://github.com/sunng87/handlebars-iron

**Comment by shinriyo** [comment]
Hello @sunng87
Thank you for replying. :smiley: 
is it official for iron?

I found before, and I tried it but it couldn't understand how to use it.

:sos: 

I added `handlebars-iron = "*"` in my Cargo.toml
I I append it.
```
    fn hello_world(_: &mut Request) -> IronResult<Response> {
        let mut resp = Response::new();
        let data = "";
        resp.set_mut(Template::new("index", data)).set_mut(status::Ok);
        Ok(resp)
    }
```
I ran `cargo run`.
I said the error.
```
error: no associated item named `new` found for type `Template` in the current scope
```
So, I tried to use `Template` struct.
`use rust-handlebars::Template;` and `use handlebars::Template;`
but, it didn't work... :cry: 

p.s. I hope minimum helloworld code in your README. :+1:

**Comment by sunng87** [comment]
This is not "official". I don't think there will be an "official" templating middleware for Iron's architecture. :smile: 

There is an example in the code tree:
https://github.com/sunng87/handlebars-iron/blob/master/examples/server.rs

Please check if it works for you.

**Comment by sunng87** [comment]
@shinriyo you data should implement `ToJson`, try

```
data = String::new()
```

**Comment by shinriyo** [comment]
@sunng87 
Thank you for replying.
I found how to use `Template`.
```
use hbs::{Template};
```

I fix like by your advice.
``
    fn hello_world(_: &mut Request) -> IronResult<Response> {
        let mut resp = Response::new();
        let data = String::new();
        resp.set_mut(Template::new("index", data)).set_mut(status::Ok);
        Ok(resp)
    }
```

I use `Router` like this
```
Iron::new(router).http("localhost:3000").unwrap();
```

However, the sample you shown said `Chain`. :exclamation:
and, in line 103 comment saids `open http://localhost:3000/abc`, but I couldn't found where `abc` defined. :astonished:

My index.html template put in /public/ folder.
must I define where is template folder by `HandlebarsEngine`? :question:

**Comment by untitaker** [comment]
I think this can be closed then.
