### ISSUE TITLE
Allow single instance middlewares

### ISSUE THREAD

**Issue by Fiedzia** [iron/iron#438]
Please allow (by redesigning or adding another type) middlewares to be single-instance types
which have before and after method. All other webframeworks work this way.

I was trying to define middleware as a struct that contains some data (dbpool in my case, but it doesn't matter). The problem is that  middlewares are held separately in self.befores and self.afters. It prevents (or at least complicates) creation of useful midllewares, forcing me to clone data, or manage pointers to separate structures - either way its more complicated than it has to be.

**Comment by KalitaAlexey** [comment]
You may add BeforeMiddleware and AfterMiddleware. If you want middleware for both ends then you may add AroundMiddleware.

**Comment by untitaker** [comment]
what @KalitaAlexey said. With that, I don't think there's anything actionable here.
