### ISSUE TITLE
How to get a value from headers using a specific key like Content-Type?

### ISSUE THREAD

**Issue by ghmlee** [iron/iron#440]
My question is that  how to get a value from headers in a request using a specific key like Content-Type?

**Comment by untitaker** [comment]
[`iron::Request`](http://ironframework.io/doc/iron/request/struct.Request.html) has a `headers` field, whose type is from [hyper](http://hyper.rs/hyper/hyper/header/struct.Headers.html).

    request.headers.get::<iron::headers::ContentType>()

This will return an instance of this struct: http://ironframework.io/doc/iron/headers/struct.ContentType.html
