### ISSUE TITLE
Hide default port in `Display` trait for `Url`.

### ISSUE THREAD

**Issue by calebmer** [iron/iron#442]
Because the `Display` is meant to be user facing, I'd like it if default ports (80 for `http` and 443 for `https`) are hidden. Currently the following is true:

```rust
assert_eq!(format!("{}", Url::parse("http://example.com").unwrap()), "http://example.com:80".to_owned());
assert_eq!(format!("{}", Url::parse("https://example.com").unwrap()), "https://example.com:443".to_owned());
```

Instead could it be the following?

```rust
assert_eq!(format!("{}", Url::parse("http://example.com").unwrap()), "http://example.com".to_owned());
assert_eq!(format!("{}", Url::parse("https://example.com").unwrap()), "https://example.com".to_owned());
```

**Comment by LFalch** [comment]
I don't see any particularly good reason not to hide the default ports.

**Comment by reem** [comment]
Yup, seems reasonable, this is also an easy task, so marking with easy so someone new has the opportunity to fix it.

**Comment by waqqas-abdulkareem** [comment]
Hi guys. 
I'm new to Rust but excited about contributing. I've done a fix for this issue and I'd like to create a pull request. Which branch do I create a request on? There seem to be only 2: "master" and "feat/autogen". I

Thanks!
