### ISSUE TITLE
Advanced OpenSSL config (client certs)

### ISSUE THREAD

**Issue by rix0rrr** [iron/iron#447]
I want to use Iron in a context where I'm required to use client certificates.

However, the OpenSSL config is quite limited now, and I'm not able to set any of the advanced configuration options.

I'd like to contribute, but I'm not sure what the best approach would be. I'm considering adding a struct to `Protocol::Https`, but that would break backwards compatibility with existing code.

I can also add a new enum variant, something like `Protocol::AdvancedHttps` with an additional struct with advanced OpenSSL options (such as client certs).

What do you think?

**Comment by sunng87** [comment]
Sorry for off-topic. I just feel the SSL thing may be out of the core scope of iron, as a web framework. In python world we saw a clear separation between servers and frameworks. I think it's time for iron developers think about #261 and #295

**Comment by rix0rrr** [comment]
I do agree, but at the same time I don't really have the time, or a choice, right now :)
