### ISSUE TITLE
how to add a new header into response at after middleware ?

### ISSUE THREAD

**Issue by Matrix-Zhang** [iron/iron#448]
such as my server's UA and the ContentType,

because of the response is immutable, i don't know how to do it

**Comment by sunng87** [comment]
You can find a working example in my [iron-json-response](https://github.com/sunng87/iron-json-response/blob/master/src/lib.rs#L69)

**Comment by untitaker** [comment]
Mutability is a property of variables in Rust, not types (except maybe for pointer types).

You can use `response.set_mut` to add modifiers to the response (Like the ones you pass to `Response::with` or `Response::set`).
