### ISSUE TITLE
Is Iron capable of determining whether a request is with or without "www"? 

### ISSUE THREAD

**Issue by jjmornim** [iron/iron#456]
How can I determine whether it's "www" or "" request to my domain on  a server? 
And how can I redirect from "www" to ""?

**Comment by phillipCouto** [comment]
You would loot at the url value in the request input to your handler.

**Comment by KenanSulayman** [comment]
You can peek into the `Host` header. Simply match that against your `www` prefixed TLD and you're ready to go

**Comment by Hoverbear** [comment]
Closing, this has been answered and there have been no followups. :)
