### ISSUE TITLE
Framework to add support for unix socket protocol

### ISSUE THREAD

**Issue by ghost** [iron/iron#458]
Sort of awkwardly worded title; right now, I would like to be able to use a unix socket to proxy an Iron server through another HTTP server. I know that such an extension is possible, because the crate [hyperlocal](https://github.com/softprops/hyperlocal) exists to add Unix socket support to Hyper. Unix sockets are beneficial because they can have permissions to only be read by certain processes.

I'm not 100% sure that the Iron framework would support this as a plugin, because the protocol is currently fixed to just HTTP and HTTPS, as far as I'm aware. If it would be possible to add support to extend this protocol, a plugin could be made to modify Iron to use Unix sockets instead of just TCP.

**Comment by chpio** [comment]
+1

**Comment by sfackler** [comment]
You can now provide an arbitrary Hyper `Listener` to Iron - does that cover this feature request?

**Comment by jlesquembre** [comment]
@sfackler could you provide an example about how to use a `Listener`? I'm also trying to use an unix socket with Iron, but I'm stuck

**Comment by phlmn** [comment]
When 0.7 is released you should be able to use hyperlocal and mount iron as service creator.
