### ISSUE TITLE
Homepage example is weird

### ISSUE THREAD

**Issue by RustyRails** [iron/iron#459]
On:
http://ironframework.io/

the main example has:
```
    Iron::new(hello_world).http("localhost:3000").unwrap();
    println!("On 3000");
```
which is a bit confusing to beginners, because the println will never actually run, I suggest it be changed to:

```
    println!("Listening on port 3000");
    Iron::new(hello_world).http("localhost:3000").unwrap();
```

**Comment by reem** [comment]
Yes! It should actually be something like:

```rust
let _server = Iron::new(hello_world).http("localhost:3000").unwrap();
println!("On 3000");
```

which would actually wait until the server is listening to print that it is listening. The problem with the current example is that the server guard is dropped immediately, instead of saved.

**Comment by shepmaster** [comment]
There appears to be a [pull request for this](https://github.com/iron/iron.github.io/pull/25).
