### ISSUE TITLE
Re-Export Modifier

### ISSUE THREAD

**Issue by kevinastone** [iron/iron#461]
Could you re-export `modifier`?  It feels like an internal implementation and I don't think it makes much sense separately adding a dependency and extern crate for `modifier` to add my own Response modifiers.

**Comment by zr40** [comment]
If you're going to depend on `modifier`, why doesn't it make sense adding it as an explicit dependency?

**Comment by kevinastone** [comment]
Because I should depend on the version from iron.  I shouldn't have to keep my modifier dependency in sync with Iron's.

**Comment by gsquire** [comment]
Is it not [already](https://github.com/iron/iron/blob/2fd6e079592ec340d8c75200bd54fde91ce34d51/src/lib.rs#L135)?

**Comment by untitaker** [comment]
Yes it is.
