### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by kevinastone** [iron/iron#462]
Any reason not to publish an new release `v0.3.1` up to Crates.io?  Would like to get the fixed URL without the standard ports (e.g. `http://example.com` instead of `http://example.com:80`) without having to use git checkouts for dependencies.

**Comment by Hoverbear** [comment]
Hi, 4.0 has been released!

**Comment by kevinastone** [comment]
Missing a tag for `0.4.0`...

**Comment by Hoverbear** [comment]
https://github.com/iron/iron/tree/0.4.0
