### ISSUE TITLE
Iron::https is undocumented

### ISSUE THREAD

**Issue by cfredric** [iron/iron#464]
Looking at http://ironframework.io/doc/iron/struct.Iron.html, there's no mention of `Iron::https`, but if you look at the Src (http://ironframework.io/doc/src/iron/src/iron.rs.html#95-184) `https` is indeed there.

I have no experience with how this documentation is generated, but my first guess is that it might have something to do with the `#[cfg(feature = "ssl")]` tag.

**Comment by badboy** [comment]
Docs are built using [this script](https://github.com/iron-bot/build-doc/blob/master/build-doc.sh).
It should build the docs using `cargo docs --features ssl` here: https://github.com/iron-bot/build-doc/blob/master/build-doc.sh#L8

**Comment by Cobrand** [comment]
Is it possible to have 2 docs generated ? One for iron with ssl features, and another for iron without ssl features ? Or maybe we can only generate with ssl features and tag them appropriately in the docs (saying that these methods / structs / ... are only available with `--features ssl` ?)

Another quick question - but maybe here is not the right place - why not make ssl a default feature that you can disable if needed ?

**Comment by Hoverbear** [comment]
#483 covers this and is in progress. Closing this in favor of that.

@Cobrand:

> Another quick question - but maybe here is not the right place - why not make ssl a default feature that you can disable if needed ?

You're welcome to create a new issue for this.
