### ISSUE TITLE
basic auth example

### ISSUE THREAD

**Issue by flosse** [iron/iron#465]
Is there an example or even middleware for basic auth?

**Comment by Hoverbear** [comment]
https://github.com/iron/session exists and may be a good starting point for this. You can also explore http://www.arewewebyet.org/topics/auth/.

If you find a way to make these integrate well with Iron please feel encouraged to write about it and report back.

**Comment by flosse** [comment]
@Hoverbear thx!

**Comment by hanusek** [comment]
https://github.com/hanusek/iron-basic-auth
