### ISSUE TITLE
Add the Content-Location header

### ISSUE THREAD

**Issue by Stebalien** [iron/iron#470]
See https://tools.ietf.org/html/rfc7231#section-3.1.4.2

**Comment by gsquire** [comment]
This may be a better issue for [hyper](https://github.com/hyperium/hyper).

**Comment by Stebalien** [comment]
Ah. I didn't realize they were pulled directly from hyper (documentation? what documentation?) :)

**Comment by Stebalien** [comment]
https://github.com/hyperium/hyper/issues/870
