### ISSUE TITLE
Cargo.toml in iron 0.3 doesn't match version in repository

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [iron/iron#471]
As of rustc 1.12.0-nightly (7333c4ac2 2016-07-31), iron 0.3 as downloaded by nightly Cargo fails to compile with the following error:

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading iron v0.3.0
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.3.0/Cargo.toml`
```

As far as I can tell, this is due to `plugin = "0.2*"` in Cargo.toml - removing the `*` causes it to compile again quite happily. This was fixed in 16c858ec2901e2992fe5e529780f59fa8ed12903 - I don't know how this is still present in the version that cargo automatically downloads.

Might it be possible to get a v0.3.1 released with this fixed?

**Comment by untitaker** [comment]
Do older Rust versions not have this problem?

On 2 August 2016 17:11:52 CEST, BenjaminGill-Metaswitch <notifications@github.com> wrote:
>As of rustc 1.12.0-nightly (7333c4ac2 2016-07-31), iron 0.3 as
>downloaded by nightly Cargo fails to compile with the following error:
>
>```
>$ cargo build
>    Updating registry `https://github.com/rust-lang/crates.io-index`
> Downloading iron v0.3.0
>error: unable to get packages from source
>
>Caused by:
>failed to parse manifest at
>`/home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.3.0/Cargo.toml`
>```
>
>As far as I can tell, this is due to `plugin = "0.2*"` in Cargo.toml -
>removing the `*` causes it to compile again quite happily. This was
>fixed in 16c858ec2901e2992fe5e529780f59fa8ed12903 - I don't know how
>this is still present in the version that cargo automatically
>downloads.
>
>Might it be possible to get a v0.3.1 released with this fixed?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/iron/iron/issues/471

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BenjaminGill-Metaswitch** [comment]
No - rustc 1.12.0-nightly (1225e122f 2016-07-30) is perfectly happy compiling iron 0.3.

**Comment by untitaker** [comment]
I'm unable to reproduce this. I can't find the broken version specifier at either [the git repo](https://github.com/rust-lang/crates.io-index/blob/master/ir/on/iron) or [the frontend](https://crates.io/crates/iron/0.3.0)

**Comment by untitaker** [comment]
Sorry, nevermind.
