### ISSUE TITLE
Displaying a response prints status message twice

### ISSUE THREAD

**Issue by Mark-Simulacrum** [iron/iron#473]
My response is displayed as:
```
HTTP/1.1 200 OK OK
Content-Length: 735
Content-Type: application/json
Access-Control-Allow-Origin: *
```

with two repeating `OK`s; this is unexpected. Perhaps I'm not expecting the right thing though--my reference is [this](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Server_response) Wikipedia article.

**Comment by untitaker** [comment]
This is a bug because the hyper status representation changed.
