### ISSUE TITLE
File as Iron Response

### ISSUE THREAD

**Issue by navidnabavi** [iron/iron#477]
Is it possible to return a file as response? 
What is the best way assuming there is no Nginx. Staticfiles package os Iron supporting only with mounting a folder. Is it possible to redirect to a static route internally like X-SEND or X-AXCEL-REDIRECt?

**Comment by gsquire** [comment]
Yes, it is.

You can use [iron's modifiers](http://ironframework.io/doc/modifier/trait.Modifier.html) in a Response like such:

```rust
extern crate iron;

use iron::prelude::*;
use iron::status;

use std::fs::File;

fn use_file(_: &mut Request) -> IronResult<Response> {
    let f = File::open("some.txt").unwrap(); // For example's sake.
    Ok(Response::with((status::Ok, f)))
}

fn main() {
    Iron::new(use_file).http("localhost:3000").unwrap();
}
```
