### ISSUE TITLE
Pass hyper instance to iron

### ISSUE THREAD

**Issue by KenanSulayman** [iron/iron#478]
Hey,

is there a way I could pass a hyper instance to iron?

This is so I could use the same hyper instance for websocket and then do iron magic on top.

Thanks! 🍻

**Comment by reem** [comment]
@adrianbrink this `Handler` is the *iron* `Handler` trait, not the hyper one. It's defined here https://github.com/iron/iron/blob/16c858ec2901e2992fe5e529780f59fa8ed12903/src/middleware/mod.rs#L57-L61.

**Comment by KenanSulayman** [comment]
It's initialized here: [src/iron.rs#L154](https://github.com/iron/iron/blob/16c858ec2901e2992fe5e529780f59fa8ed12903/src/iron.rs#L154).

I'd go with something like this:

```
pub fn listen_with<A: ToSocketAddrs, S: Server::http + Server::https>(
    mut self, server: S, addr: A, threads: usize,
    protocol: Protocol, timeouts: Option<Timeouts>
) -> HttpResult<Listening> {
```

**Comment by adrianbrink** [comment]
How come that we also implement the Handler trait from hyper.

`impl<H: Handler> ::hyper::server::Handler for Iron<H> {`

in [iron.rs](https://github.com/iron/iron/blob/master/src/iron.rs)

**Comment by KenanSulayman** [comment]
It effectively sends the request to the Händler functions and processes the output. The instantiation is still in listen_with

**Comment by phlmn** [comment]
Since hyper 0.12 and #523 this is possible. Iron now implements the `NewService` trait from hyper.

This is also how `Hyper::http(…)` now works. (`self` is Iron)

```rust
    pub fn http<A>(mut self, addr: A)
    where
        A: ToSocketAddrs,
    {
        let addr: SocketAddr = addr.to_socket_addrs().unwrap().next().unwrap();
        self.local_address = Some(addr);

        let server = Server::bind(&addr)
            .tcp_keepalive(self.timeouts.keep_alive)
            .serve(self)
            .map_err(|e| eprintln!("server error: {}", e));

        hyper::rt::run(server);
    }
```
