### ISSUE TITLE
Cannot upload form multipart data over 512kB

### ISSUE THREAD

**Issue by vojtechkral** [iron/iron#480]
Hi,
  I'm not sure if this is an Iron or Hyper problem, but I'm unable to upload a file using html form if the file size is over 512kB using Chromium.

File with size of 512kB or less are uploaded fine. When using Firefox, files larger than 512kB can be uploaded just fine.

There's no error, there's nothing strange in the debug log, but Request body cannot be read and according to Chromium the request is failed with no status (no data received apparently).

Request headers:
```
Accept-Encoding: gzip, deflate
Accept-Language: cs,en;q=0.8,sk;q=0.6
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 524581
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRR14SThvtMDr9z5d
Host: localhost:3000
Origin: http://localhost:3000
Pragma: no-cache
Referer: http://localhost:3000/
Upgrade-Insecure-Requests: 1, 
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
DNT: 1
```

**Comment by Hoverbear** [comment]
Hi! Thanks for raising this. Any chance you could provide the headers which Firefox sends (but succeeds) as well? Maybe there is a difference.

**Comment by vojtechkral** [comment]
Firefox headers:

```
Accept-Encoding: gzip, deflate
Accept-Language: cs-CZ,en-GB;q=0.8,en-US;q=0.5,en;q=0.3
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Content-Length: 524626
Content-Type: multipart/form-data; boundary=---------------------------24775772147415635372086994
DNT: 1
Host: localhost:3000
Referer: http://localhost:3000/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

... I don't really see a difference appart maybe from the cache

**Comment by vojtechkral** [comment]
I also noticed this only happens with `multipart/form-data`, when I send the data appended to the request raw, there's no problem even with much larger files.

**Comment by Hoverbear** [comment]
I see a difference in the `Content-Type` field. 

```
Content-Type: multipart/form-data; boundary=---------------------------24775772147415635372086994
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRR14SThvtMDr9z5d
```

Hmm...

**Comment by vojtechkral** [comment]
Hi. I managed to fixed this - the problem was actually on the front end where the body payload was embeded in a wrong encoding. Damn JavaScript. Sorry for the noise!

**Comment by Hoverbear** [comment]
Hey that's great! I'm glad. I was actually talking with a colleague about this today! Haha
