### ISSUE TITLE
ssl feature is not documented in online docs

### ISSUE THREAD

**Issue by vignesh-sankaran** [iron/iron#483]
Struggling to figure out how to start up Iron with HTTPS rather than the default HTTP. Do we also need to provide security certificates, or is that generated by Hyper?

**Comment by untitaker** [comment]
If you build Iron with the `ssl` feature, you get the `https` method which takes a path to certificate and key.

@reem I'd like to modify the iron-bot script, could it be moved to the iron org?

**Comment by reem** [comment]
@untitaker so awkward situation but I appear to have lost the password for iron-bot, I'll keep looking into it and update you

**Comment by Hoverbear** [comment]
@vignesh-sankaran You'll need your own security certificates. I suggest using https://letsencrypt.org/ for this purpose since it's free and you don't need to deal with a crusty CA.

**Comment by vignesh-sankaran** [comment]
@Hoverbear Yep I do plan on using LE but am generating my own certs with OpenSSL in the dev environment for now

Thanks @untitaker, that did the trick

**Comment by Hoverbear** [comment]
Just wanted to check, @reem. Any progress?

It may be worth looking at alternatives for documentation anyways. For example, http://docs.rs/

**Comment by untitaker** [comment]
I don't think `docs.rs` is any more flexible. I doubt that you can configure features at all.

**Comment by Hoverbear** [comment]
(I'd be willing to argue that a feature such as `https` should be opt-out rather than opt-in)

**Comment by untitaker** [comment]
We already had it on by default, with the effect that it was impossible to disable because every extension implicitly depended on it when depending on standard Iron.

On 6 October 2016 22:59:47 CEST, Andrew Hobden <notifications@github.com> wrote:
>(I'd be willing to argue that a feature such as `https` should be
>opt-out rather than opt-in)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iron/iron/issues/483#issuecomment-252086996

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by reem** [comment]
Better yet just moved the repo over to https://github.com/iron/build-doc

**Comment by untitaker** [comment]
I fixed up the ssl feature stuff, but it appears deployment in general fails, see the current travis build: https://travis-ci.org/iron/iron/jobs/173813466#L1279

**Comment by Hoverbear** [comment]
Doh!
