### ISSUE TITLE
Connection refused with JVM client

### ISSUE THREAD

**Issue by Synesso** [iron/iron#484]
```
git clone https://github.com/iron/iron.git
(cd iron && cargo run --example hello)
```

```
$ curl "http://localhost:3000/"
Hello world!
```

but

```
$ scala
scala> scala.io.Source.fromURL("http://localhost:3000/").mkString
java.net.ConnectException: Connection refused
```

I found this issue when my own Iron app suddenly stopped accepting requests. I raised a [stackoverflow question](http://stackoverflow.com/questions/39781623/localhost-iron-server-curl-connects-but-scala-cannot), but then it started working again. A few hours later, the app is no longer accepting requests from the JVM once more.

* OSX 10.11.6
* cargo 0.13.0-nightly (9399229 2016-09-14)

also tested with

* cargo 0.13.0-nightly (19cfb67 2016-09-28)

**Comment by untitaker** [comment]
Do other clients work while the JVM client fails?

**Comment by Synesso** [comment]
Yes, curl works.

Also, if I run `python -m SimpleHTTPServer`, I can access those pages from
Scala OK.

**Comment by Hoverbear** [comment]
Can you confirm that it is still an intermittent problem if you connect from 127.0.0.1?

**Comment by Hoverbear** [comment]
Could it be related to #476?

**Comment by Synesso** [comment]
I can confirm that it worked with my app at some stage, and then stopped
again. I have not yet seen it work once more. I did not capture the changes
which flipped it from working to not working and back again, but I wasn't
touching networking code in either client or server app.

**Comment by Synesso** [comment]
If I modify hello.rs to bind to 127.0.0.1 instead of localhost, it works
from Scala with either 127.0.0.1 or localhost.
Whilst hello.rs binds to localhost, nothing works from Scala (yet works
from curl).

**Comment by Hoverbear** [comment]
Okay can you give me the output of your hosts file? Please see this comment from @untitaker https://github.com/iron/iron/issues/476#issuecomment-241730172

**Comment by Synesso** [comment]
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost
#127.0.0.1 art.local
255.255.255.255 broadcasthost
::1             localhost


I commented out the last line and it now works. So yes, same issue.

Thank you

**Comment by Hoverbear** [comment]
Okay, perfect. So this issue is resolved then? Can we close this?

**Comment by Synesso** [comment]
Indeed!
