### ISSUE TITLE
Website not show on public

### ISSUE THREAD

**Issue by kocoten1992** [iron/iron#493]
Here is what I've try:

The code is:
```
extern crate iron;

use iron::prelude::*;
use iron::status;

fn main() {
    Iron::new(|_: &mut Request| {
        Ok(Response::with((status::Ok, "Hello World!")))
    }).http("somecooldomain.dev:80").unwrap();
}
```

change in hosts file, /etc/hosts (ubuntu)
```
127.0.0.1 somecooldomain.dev
127.0.0.1 www.somecooldomain.dev
```

After this point, I try somecooldomain.dev on my local ubuntu, it display very fine, this is what I did next, on router I map port 80 router to my ubuntu machine 80, 80->80

Then I go to another computer (windows OS, on a different network), I change in hosts file, windows/system32/drivers/etc/hosts
```
public.ipv4.ubuntu.machine somecooldomain.dev
public.ipv4.ubuntu.machine www.somecooldomain.dev
```

But when on I try access ```somecooldomain.dev``` on my window machine, somehow it doesn't work

It said This site can’t be reached, ERR_CONNECTION_REFUSED, not sure what is going on here :(

Please help me, thanks a lot in advance :D

**Comment by Hoverbear** [comment]
This is probably because `somecooldomain.dev:80` is mapped to `127.0.0.1:80`. `127.0.0.1` means "only on the local host". :)

Can you try doing `.http("0.0.0.0:80")` instead?

**Comment by kocoten1992** [comment]
It working again, thank you :+1:

**Comment by Hoverbear** [comment]
Awesome!
