### ISSUE TITLE
Add a link to the annotated clippy service docs.

### ISSUE THREAD

**Issue by echochamber** [iron/iron#499]
I only happened to find [this link](https://clippy.bashy.io/docs/) when I was reading arewewebyet.com. Seems like something that should be linked in the README

**Comment by Hoverbear** [comment]
Can you explain why? This isn't the clippy repo.

**Comment by echochamber** [comment]
Its not uncommon for libraries/frameworks to link to other projects that were built using those. Its the only "real world" example of a site built with iron I've seen so far.

**Comment by untitaker** [comment]
Ah, yeah. I think we should totally link to this on the website (but not in this repo)
