### ISSUE TITLE
[feature request/documentation problem] can/do we have a convenience function for making a simple IronError from a String

### ISSUE THREAD

**Issue by makoConstruct** [iron/iron#502]
Can we get a convenience function for creating an IronError from a String? It seems like the most concise way to do this currently is:

```
struct StringError(String);
impl fmt::Display for StringError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Debug::fmt(self, f)
    }
}
impl Error for StringError {
    fn description(&self) -> &str { &*self.0 }
}

fn ironError(msg:String)-> IronError {
    IronError::new(StringError(msg), iron::status::BadRequest)
}
```

Which seems implausibly inconvenient and I wonder if I'm just missing something. If I am missing something, please add a note to http://ironframework.io/doc/iron/error/struct.IronError.html?search= to indicate that there is an easier way to produce them.

**Comment by Hoverbear** [comment]
Hrm, we could maybe implement [`From`](https://doc.rust-lang.org/book/error-handling.html#the-from-trait) for `String`...

**Comment by untitaker** [comment]
I recommend using `error-chain` for proper errorhandling. Creating simple stringly-typed errors is an antipattern (not specific to Rust), and error-chain helps with that.
