### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by ysimonson** [iron/iron#505]
Hi! I found a couple of issues browsing the documentation:

1) Certain pages are unstyled. e.g.: http://ironframework.io/doc/urlencoded/type.QueryMap.html
2) Some things are documented twice. See `query_pairs` in [this search result](http://ironframework.io/doc/url/struct.Url.html?search=query). Maybe this is fixed by the [latest commit](https://github.com/iron/iron/commit/cfd484652431d196650ecb0f43ea8556306d2af4)?

**Comment by Hoverbear** [comment]
Hrm, it looks like the rustdoc.css is never being pulled in...

**Comment by untitaker** [comment]
We now use docs.rs. Unfortunately this link doesn't work, but the base URL `/doc/urlencoded/` does at least.
