### ISSUE TITLE
doc is outdated

### ISSUE THREAD

**Issue by bbigras** [iron/iron#507]
I don't see WriteBody in the documentation on http://ironframework.io/doc/iron/

**Comment by Hoverbear** [comment]
In the meantime you can reference https://docs.rs/iron/0.4.0/iron/?search=writebody

**Comment by zoumi** [comment]
http://ironframework.io/doc/iron/headers/struct.Cookie.html
iron::headers::Cookie should be Cookie(pub Vec<Cookie>) in hyper
not Cookie{...} in crate cookie

**Comment by untitaker** [comment]
Now everything redirects to docs.rs! Two things need to be done:

* Remove `build-docs.sh` from all CI configurations
* Add missing redirects
