### ISSUE TITLE
Re-export url crate

### ISSUE THREAD

**Issue by gsquire** [iron/iron#514]
I know the names are conflicting, but it would be helpful to re-export the url crate's `Url` type. I found it unfortunate that I had to import the url crate to use the `Into` trait for iron's `Url`.

This came after the deprecation of `into_generic_url` in 0.4.1.

**Comment by untitaker** [comment]
Thanks, I'll wait 1-2 days until I do a bugfix release (perhaps there are more things I've missed).

**Comment by gsquire** [comment]
No problem! Thanks for adding it in.
