### ISSUE TITLE
Redirect to desired page after login possible? 

### ISSUE THREAD

**Issue by Boscop** [iron/iron#517]
Let's say the user tries to access /post/42/edit but isn't logged in, so he isn't allowed to edit the post, it's easy to redirect him to /login but how to redirect to the original endpoint /post/42/edit after successful login (such that the usual checks are done that are done when accessing the url while logged in, e.g. that the user is owner of the post). 
I think the original path has to be passed to /login as a parameter like /login/:target, and the handler for /login extracts it and redirects. Can url segment parameters like this contain  slashes or should it be a URL encoded GET parameter? 
How can a request handler access the target path to pass to /login? 

Is it just `request.url`?

**Comment by untitaker** [comment]
> I think the original path has to be passed to /login as a parameter like /login/:target, and the handler for /login extracts it and redirects. Can url segment parameters like this contain  slashes or should it be a URL encoded GET parameter? 

That is correct, though you would rather use a query parameter (the part after
the ?) for this. Look at how GitHub does it, for example.

**Comment by Boscop** [comment]
Thanks!
