### ISSUE TITLE
Listen on multiple ports?

### ISSUE THREAD

**Issue by lilith** [iron/iron#520]
Is there a common pattern for listening on multiple ports (say 80 and 443), while preferably sharing the same threadpool?

**Comment by Hoverbear** [comment]
Hm... Not to my knowledge at this moment. One possibility is just listening on 443 with a second Iron instance and proxying it to the 80.

**Comment by phlmn** [comment]
When 0.7 is released you might be able to configure hyper to listen to multiple ports and then mount iron as service creator.
