### ISSUE TITLE
In which style to use iron is recommended?

### ISSUE THREAD

**Issue by hicqu** [iron/iron#524]
Iron is a wonderful web framework. But how to use it in product environment?
1.  Directly listen on 80(or 443 for https), 200 threads in one process;
2.  Directly listen on web ports, 20 threads per process, 10 processes(with REUSEPORT socketopt on Linux);
3.  Directly listen on web ports, 20 threads per process, prefork 10 processes;
4.  Listen on other ports, and using nginx as reverse proxy;
5.  Listen on other ports, and using nginx as reverse proxy, and using UWSGI between iron and nginx;

1, 2, and 3 are very similar.

we don't consider that nginx can have many upstreams, because we can also implement horizontal expansion by DNS level.

So, which style is best?

**Comment by untitaker** [comment]
All of the above are fine, though having multiple processes appears to be overkill for me (the server really restarts fast enough).

**Comment by phlmn** [comment]
Seems answered.
