### ISSUE TITLE
Why not use rustfmt?

### ISSUE THREAD

**Issue by dorfsmay** [iron/iron#532]
Is there a reason why iron/iron code does not comply with rustfmt format?

It means that those of us who use rustfmt plug-ins have to disable the plug-ins from our editors before we can work on this project. It also open space for discussions about style...

I'm happy to create a Pull Request for this, but first want to know if there's a reason for not using it.

**Comment by untitaker** [comment]
Feel free to open a PR and cc me

**Comment by Hoverbear** [comment]
I'm concerned this will make merging #523 etc very hard.

**Comment by dorfsmay** [comment]
@Hoverbear Would make sense to cancel this PR (there really was no worked involved), put a moratorium on big PRs until the current ones are being merged, and start this initiative again after that?

**Comment by untitaker** [comment]
agreed with @dorfsmay, this could be done in either order. It doesn't matter tbh.

**Comment by MJDSys** [comment]
@dorfsmay @untitaker I'm happy to do whatever as well.  If you wish to merge #533 first, I can rebase on top of that, maintaining the rustfmt runs.  In fact I suspect there is some git trickery I could do to make that trivial :).

Or we can merge #523, then redo #533 on top.  Whatever works for the iron project.

**Comment by phlmn** [comment]
Since #523 is merged, I will now run rustfmt on all files :)
