### ISSUE TITLE
Why are cookie and seesion in the graveyard? Recomended way to deal with cookies?

### ISSUE THREAD

**Issue by dorfsmay** [iron/iron#536]
Both the cookie and session plugin are in an org called "iron-graveyard", self-described as "A holding site for old, deprecated iron packages.".

- The README.md in iron/iron links to iron/session and iron/cookie, but there's then a redirection to iron-graveyard. Is that ok? It is confusing, it looks as though those are current official plugins, but then show plugins that are said to be "deprecated". Should this be changed?

- What is the recomended way to deal with cookies in the current version of iron?

**Comment by untitaker** [comment]
The most current session management crate is `iron-sessionstorage`. The other ones are unmaintained.

**Comment by untitaker** [comment]
I just updated the README for this. Please point out other bad links.

**Comment by dorfsmay** [comment]
https://docs.rs/iron/0.5.1/iron-sessionstorage redirects to https://docs.rs/iron/0.5.1/iron/

No mention of session nor cookies anywhere in that page.

**Comment by dorfsmay** [comment]
I cloned the iron-session repo, "cargo doc" and went through it's documentation.

There is no easy was to get the value of a cookie outside of a session. Cookies are used for a lot of things outside session, turning feature flags on, routing in blue/green environment, etc...

Also, cookies are just a form of sepcialised header. As far as I am concerned, iron/headers is missing the concept of cookies. It deals with the http header/concept of "Set-Cookie" with https://docs.rs/iron/0.5.1/iron/headers/struct.SetCookie.html but does not deal at all with http header/concept of "Cookie", even though it is one of the most used header on the internet!

Can we add that concept directly into iron/headers? Are there any strong objections to it (don't want to waste time on a PR that'll be rejected on philosophical ground)?

**Comment by untitaker** [comment]
Iron has structs for Cookie and Set-Cookie if that is the kind of low-level access you need. Otherwise I don't see why you can't use iron-sessionstorage for the usecases you described. It exposes a key-value storage interface that supports the operations you want, and it can be set up to use signed cookies underneath.

Where did you find the URL for iron-sessionstorage that doesn't work?

On April 15, 2017 4:51:23 PM GMT+02:00, Yves Dorfsman <notifications@github.com> wrote:
>I cloned the iron-session repo, "cargo doc" and went through it's
>documentation.
>
>There is no easy was to get the value of a cookie outside of a session.
>Cookies are used for a lot of things outside session, turning feature
>flags on, routing in blue/green environment, etc...
>
>Also, cookies are just a form of sepcialised header. As far as I am
>concerned, iron/headers is missing the concept of cookies. It deals
>with the http header/concept of "Set-Cookie" with
>https://docs.rs/iron/0.5.1/iron/headers/struct.SetCookie.html but does
>not deal at all with http header/concept of "Cookie", even though it is
>one of the most used header on the internet!
>
>Can we add that concept directly into iron/headers? Are there any
>strong objections to it (don't want to waste time on a PR that'll be
>rejected on philosophical ground)?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/iron/iron/issues/536#issuecomment-294297974

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
BTW the correct doc url for iron-sessionstorage is https://docs.rs/iron-sessionstorage

**Comment by dorfsmay** [comment]
Thanks for the link to iron-sessionstorage doc. No bad link, I had gone to iron docs, and replaced the name, so my own fault.

`Iron has structs for Cookie and Set-Cookie`

I must be missing something. I hate to ask for things I should be able to find myself, but can you point me to Iron's struct for "cookie"?

I cannot find it in the doc. I did a fetch/pull on iron and "ag -i cookie" is not return anything.

**Comment by untitaker** [comment]
On Sat, Apr 15, 2017 at 08:46:51AM -0700, Yves Dorfsman wrote:
> I must be missing something. I hate to ask for things I should be able to find myself, but can you point me to Iron's struct for "cookie"?

https://docs.rs/iron/0.5.1/iron/headers/struct.Cookie.html

I recommend using the search on the site itself, it has worked well for me.
