### ISSUE TITLE
Unicase should be re-exported.

### ISSUE THREAD

**Issue by quadrupleslap** [iron/iron#541]
`pub struct AccessControlAllowHeaders(pub Vec<UniCase<String>>);`

**Comment by untitaker** [comment]
Yes it should be here. Headers are case-insensitive.

**Comment by quadrupleslap** [comment]
Sorry, I was trying to ask if UniCase was only being used in comparisons, and so didn't need to be exposed by the external API. This is very slightly annoying because it means you sometimes have to add a `unicase` dependency to `Cargo.toml` just to add a single header.

**Comment by untitaker** [comment]
Right, we should probably reexport unicase from hyper.

**Comment by sanpii** [comment]
For information, iron requires unicase 1.4 (not 2.0).

**Comment by phlmn** [comment]
Obsolete
