### ISSUE TITLE
How to add my SSL cert, say from certbot?

### ISSUE THREAD

**Issue by dessalines** [iron/iron#546]
I don't see any instructions for how to ssl-enable / add `https` support.

**Comment by yinpeng** [comment]
A reverse proxy like nginx server may help you.

**Comment by dessalines** [comment]
No reason to use nginx if Iron is already a webserver. Every webserver should have ssl support.

**Comment by piedoom** [comment]
Pardon if I'm wrong, but in production wouldn't you almost always want to use an nginx reverse proxy to the application?

**Comment by sfackler** [comment]
Even if you want an nginx at the front door, you may still want to encrypt the in-network communications of the server and whatever else it's talking to.

**Comment by dessalines** [comment]
Not really. You can use linux routing tables to redirect incoming traffic to your application's web server port, so adding an extra layer is entirely unnecessary.

**Comment by phlmn** [comment]
When 0.7 is release you can configure hyper to use https and mount iron as service creator. (See https://github.com/tokio-rs/tokio-tls/blob/master/examples/hyper-server.rs)
