### ISSUE TITLE
Release 0.6.0 with changes on master

### ISSUE THREAD

**Issue by robinst** [iron/iron#551]
(From the comments here: https://github.com/iron/iron/pull/544#issuecomment-303621983)

It would be cool to get a 0.6.0 release with the changes in master since 0.5.1 (from January): https://github.com/iron/iron/compare/0.5.1...master

The following would be worth releasing:

* Dependency cleanups: https://github.com/iron/iron/compare/0.5.1...master#diff-80398c5faae3c069e4e6aa2ed11b28c0
* API change to use `std::error::Error`: https://github.com/iron/iron/compare/0.5.1...master#diff-9a269209bed069ffb36d5565a91c9840
* Documentation improvements

(It would be before hyper 0.11, as changing Iron to be based on async hyper will probably take a while.)

**Update:** iron 0.6.0 has been released. Now the iron dependency needs to be bumped to "0.6" in all the other iron crates (and released):

- [x] [router](https://github.com/iron/router): https://github.com/iron/router/pull/141
- [x] [mount](https://github.com/iron/mount): https://github.com/iron/mount/pull/95
- [x] [persistent](https://github.com/iron/persistent): https://github.com/iron/persistent/pull/64 / https://github.com/iron/persistent/pull/65
- [x] [bodyparser](https://github.com/iron/body-parser) (depends on persistent): https://github.com/iron/body-parser/pull/79
- [x] [urlencoded](https://github.com/iron/urlencoded) (depends on bodyparser): https://github.com/iron/urlencoded/pull/72
- [x] [params](https://github.com/iron/params) (depends on bodyparser and urlencoded) https://github.com/iron/params/pull/39
- [x] [iron-test](https://github.com/iron/iron-test) (depends on router, urlencoded) https://github.com/iron/iron-test/pull/47
- [x] [staticfile](https://github.com/iron/staticfile) (depends on mount, iron-test) https://github.com/iron/staticfile/pull/100
- [x] [logger](https://github.com/iron/logger)

While we're at it, we should bump other dependencies as well if needed.

**Comment by robinst** [comment]
@reem @untitaker ?

**Comment by robinst** [comment]
See here for why this is being held up (problems with permissions on crates.io): https://github.com/iron/urlencoded/issues/68

**Comment by Hoverbear** [comment]
Ping @reem

**Comment by cetra3** [comment]
What's the status of this request? Looks like the urlencoded stuff has been resolved?

**Comment by untitaker** [comment]
I released Iron 0.6.0, please file PRs with me in cc for extension updates.

**Comment by robinst** [comment]
@untitaker thank you! Here's a pull request for router: https://github.com/iron/router/pull/141

**Comment by shepmaster** [comment]
- [ ] [iron-test](https://github.com/iron/iron-test) (depends on router, urlencoded)

**Comment by robinst** [comment]
Thanks @shepmaster, added to the list. And staticfile depends on iron-test..

**Comment by jebrosen** [comment]
Additionally, [logger](https://github.com/iron/logger) has already been updated for iron 0.6.0 but has not been published yet.

**Comment by untitaker** [comment]
Will release logger 0.4.0

**Comment by robinst** [comment]
After about 6 months, I think we're done now.

I'm thinking about raising a pull request to add some text to the README saying that iron is not actively maintained and you should consider migrating to something else. Thoughts?
