### ISSUE TITLE
Read from WriteBody

### ISSUE THREAD

**Issue by selaux** [iron/iron#553]
Hi. I'm currently implementing a compression middleware for iron: https://github.com/selaux/iron-pack

In order to do this I am reading from `res.body` in a `AfterMiddleware` and compressing the result using a `Modifier`. Unfortunately `WriteBody` does not implement `Read`, so the only way is to write the whole body somewhere first, which I would like to avoid. Is there any way that `Read` could be implemented for `WriteBody`? I tried already, but I dont know how to approach this correctly. Would this be valid for a PR? And if so, could you point me into a direction on how to start with this 🙂 ?

**Comment by sfackler** [comment]
See here for an example of how to do this: https://github.com/iron/iron/issues/548#issuecomment-305829393

**Comment by selaux** [comment]
Thanks, that was what I was looking for. Sorry for not searching first properly 😉 .
