### ISSUE TITLE
Reading `req.body` has huge performance lack

### ISSUE THREAD

**Issue by oldaniel** [iron/iron#557]
So, I am currently coding with **iron** (the web framework), since it is web stuff I want to read the users request body. And that's where I ran into damn big issues.

Wether I use `io::Read` or `io::BufReader`, wether I use `.read()`, `.read_to_end()` or `.read_to_string()`, my benchmark went from ~290k (without read) down to ~112 requests per second.

Example code:
```rust
fn hello(req: &mut Request) -> IronResult<Response> {
    let mut body = String::new();
    let mut bytes = Vec::new();
    let mut lbytes = vec![0;100];

    // NOTICE: I checked, those reads are successful and return the correct value.
    req.body.read_to_end(&mut bytes).unwrap();
    // Or
    req.body.read(&mut lbytes).unwrap();
    // Or
    req.body.read_to_string(&mut body).unwrap();

    Ok(Response::with((status::Ok, "Hello World!")))
}
```

**Does anyone have a workaround for the same issues? Is there maybe a duplicate question I didn't found? Is this issue known?**

**Comment by oldaniel** [comment]
@plumenator I did a POST request with a normal user login, about 40bytes. I haven't been working in rust for a while, so yeah. For more research I need some time.

**Comment by oldaniel** [comment]
@plumenator I tested your code, and it works now. I really have no idea what I did wrong, cause it works with the same code now. Reached ~320k requests per second again. Thanks.

**Comment by plumenator** [comment]
Good to know!
