### ISSUE TITLE
Support `Warning` header

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [iron/iron#558]
Iron currently seems to lack support for the [`Warning` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning). I haven't checked if there are any others missing.

**Comment by mrenoon** [comment]
It seems that this is due to the hyper version used in hyper is 0.10 which does not support Warning header yet. However, when you are dealing with a `headers: &mut Headers` , you can get/set the raw Warning headers like so:
```
let warnings = match headers.get_raw("Warning") {
        Some(warning) => std::str::from_utf8(&warning[0]).unwrap(),
        None => "No warning.".to_string(),
};
```
```
headers.set_raw("Warning", vec![b"Warning: 110".to_vec()]);
```

**Comment by phlmn** [comment]
Should be fixed with new hyper version.
