### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by phlmn** [iron/iron#578]
Hey,

I would like to suggest looking for new maintainers rather than recommending to fork iron (as in #576). I don't think a fork would gain the popularity of iron in any reasonable amount of time. This framework has done so much right and I think it is important to have a web framework that is based on another concept than Rocket for example.

What about changing the "NOTE: Iron is not actively maintained at the moment, please consider using a different framework" to "NOTE: Iron is looking for maintainers." and maybe let people express their interest in maintaining iron in this issue? I think there are quite some future maintainers that just need to know their wanted for this project.

I want to set a good example by saying "I am very interested in maintaining iron!".

@reem @zzmp @untitaker

**Comment by ernestas-poskus** [comment]
> NOTE: Iron is looking for maintainers.

very good idea :hearts:

**Comment by zzmp** [comment]
I am for new maintainers. I think it's much healthier for a project to be passed on to its users than forked ad infinitum.

I haven't been involved in a long while, but if there's anything I can do to move this along LMK.
I'll reach out to @reem directly and make sure he sees this, too.

**Comment by insha** [comment]
I too am very interested in maintaining iron.

**Comment by phlmn** [comment]
@reem any feedback on this?

**Comment by reem** [comment]
I am for it, unfortunately I just don't have time to maintain iron myself these days. If someone would like to compile a list of packages or permissions they need, I can try to get through it in a timely manner. I would prefer to hand iron over to someone with some level of experience in the open source/rust community, or better yet a group of people, but I won't be too picky.

**Comment by Weasy666** [comment]
So...any news on the handover? It really would be a shame to silently let this framework die.

@zgtm @reem @phlmn

**Comment by reem** [comment]
@zgtm @phlmn if I get confirmation from you two I'll add you both to the aforementioned list of projects, just comment back in this thread

**Comment by phlmn** [comment]
@reem The list looks good and I'm still interested. *Confirmed!* :)

**Comment by zgtm** [comment]
@reem _Confirmed_ as well! Thank you!

**Comment by reem** [comment]
I've added you both to the iron organization and the `dev-team` team, I'll add `dev-team` to all of those other listed crates and add you to those repos as well later today - will update this comment when it's done.

**Comment by phlmn** [comment]
@reem is it done?

**Comment by remram44** [comment]
Looks like this happened. Congratulations to the new maintainers, and thanks for taking this over! It would have been truly sad to see this project die or undergo a painful renaming because of lack of permissions.

**Comment by e-oz** [comment]
I think this issue can be closed safely to don't scare people.

**Comment by phlmn** [comment]
@e-oz You're right! 😄
