### ISSUE TITLE
I'm looking to contribute

### ISSUE THREAD

**Issue by ChristopherLClark** [iron/iron#596]
Would anyone have some thoughts/ideas on how we could incorporate what a lot of advanced frameworks have, like inject-able const values for settings (spring cloud config). Dependency Injection. Services etc.

**Comment by phlmn** [comment]
Iron is pretty light weight, I don't think dependency injection should be part of it. It should rather be designed flexible enough to work with a dependency injection library.

In general if you want to discuss a specific feature please create an issue for that, this is very welcome! 🙂
