### ISSUE TITLE
about "too many open file"

### ISSUE THREAD

**Issue by pili2026** [iron/iron#608]
I built the server for testing, but I found that when the client requests too much, it will produce "too many open file" problems.
I also use ulimit to increase the number of open files, but it will still produce the same problem.

But I found that hyper version 12.xx has a new set_sleep_on_errors function to solve the problem of (?) EMFILE. However, the hyper dependent version of iron ver 0.6.0 is ver 0.10. Would you like to continue to update?

Maybe not the above problem, but this is the relevant solution I have found so far...

**Comment by dvic** [comment]
You can try the master version of Iron and see if that solves your problem (it uses Hyper 0.12).

**Comment by pili2026** [comment]
Hello,master version means `Iron = "0.6.0"` 
or
```
[dependencies.iron]
version = "*"
```?

**Comment by dvic** [comment]
You can specify it as

`iron = { git = "https://github.com/iron/iron", branch = "master" }`

The `, branch = "master"` is optional (this is the default).

**Comment by pili2026** [comment]
Ok,let me try it.
Thank
