### ISSUE TITLE
Unable to build on nightly

### ISSUE THREAD

**Issue by miller-time** [iron/iron#615]
per recent travis CI: trait objects without an explicit `dyn` are deprecated

it seems this is a warning for `cargo build` but an error for `cargo test`

**Comment by miller-time** [comment]
@phlmn speedy! thanks :)

**Comment by miller-time** [comment]
@phlmn any plans to publish to crates.io in the near future?

**Comment by phlmn** [comment]
> @phlmn speedy! thanks :)

You're welcome!

> @phlmn any plans to publish to crates.io in the near future?

Yeah for sure! (At least we thought) We were missing rights to do so, but seems like we do have them. 

I think I will finish https://github.com/iron/iron/issues/579, which makes releasing easier, and at least release a `0.7-pre` version very soon. For `0.7` we should be sure about the breaking changes.
