### ISSUE TITLE
iron::params not parsing query string parameters in 0.6.1 UrlEncodedQuery seems to work with same example.

### ISSUE THREAD

**Issue by klmallory** [iron/iron#617]
I'm having trouble getting the example in the documentation to work. Even the examples throw errors. UrlEncodedQuery parses fine, no problems. Is Params still supported?

Url: 
http://localhost:5000/myApiEndpoint?name=jason&age=2

Handler:
fn getStatesByCountryId(req: &mut Request) -> IronResult<Response>{ ...

Code:

        println!("Params = {:?}", req.get_ref::<Params>());

        match req.get_ref::<UrlEncodedQuery>() {
            Ok(ref hashmap) => println!("Parsed GET request query string:\n {:?}", hashmap),
            Err(ref e) => println!("{:?}", e)
        };

Output:

Params = Err(InvalidPath)
Parsed GET request query string:
 {"name": ["jason"], "age": ["2"]}

**Comment by phlmn** [comment]
Sounds like #604
