### ISSUE TITLE
Typo in documentation link (modifiers)

### ISSUE THREAD

**Issue by tmpolaczyk** [iron/iron#618]
https://github.com/iron/iron/blob/e3e8720fa3be21bfde94985013c55503eed5b0b3/iron/src/modifiers.rs#L45

Should probably point to https://github.com/iron/iron/blob/master/iron/src/modifiers.rs

**Comment by phlmn** [comment]
Oh yes, the path has changed as part of #579.

**Comment by tymtam2** [comment]
This should be closed now.
