### ISSUE TITLE
question: Is this repo still in active development?

### ISSUE THREAD

**Issue by renannprado** [iron/iron#621]
Is this repo still in active development? And if so, who are the users that have the rights to review/merge pull requests?

cc @phlmn which is the only one I know for sure can merge.

**Comment by arxra** [comment]
I'm taking the lack of response to this issue as a no :/

**Comment by phlmn** [comment]
It is in development, but I only find time occasionally. 😕

**Comment by renannprado** [comment]
@phlmn don't you want to try to find in the community more people that can help you to maintain?
