### ISSUE TITLE
ironframework.io not resolving

### ISSUE THREAD

**Issue by mcsaucy** [iron/iron#629]
Looks like it's still registered:
```
[mcsaucy@caelum]~❯ whois ironframework.io | grep Expiry
Registry Expiry Date: 2021-06-24T17:11:26Z
```
Just not resolving:
```
[mcsaucy@caelum]~❯ dig @8.8.8.8 ironframework.io | grep NXDOMAIN
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25397
[mcsaucy@caelum]~❯ dig @1.1.1.1 ironframework.io | grep NXDOMAIN
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 38408
```

**Comment by dataf3l** [comment]
Hi guys, I'm facing the same issue.
I was like, wtf....
who will fix this???

**Comment by hedgehog1029** [comment]
`Creation Date: 2020-09-22T14:31:19Z`

the creation date is September, now, so I reckon it got dropped and picked up by a bot automatically. seems to issue some redirects at the moment

**Comment by theptrk** [comment]
Thanks for the issues. This domain was taken by and serving malicious content so we will strike the links from the README until it has a new home. Ref: https://github.com/iron/iron/issues/632
