### ISSUE TITLE
`req.url` stripping fragments?

### ISSUE THREAD

**Issue by hjfitz** [iron/iron#642]
I'm trying to build an application that uses fragments, but I can't get a handle on them in my handler. Is this intentional? I can't see any call/method that would let me get access to fragments as part of a handler.

A really basic example:
```rs
use iron::prelude::*;

fn hello_world(req: &mut Request) -> IronResult<Response> {
    println!("got url: {}", req.url);
    Ok(Response::with((iron::status::Ok, "Hello World")))
}

fn main() {
    let chain = Chain::new(hello_world);
    Iron::new(chain).http("localhost:3000").unwrap();
}
```

When calling `GET /#tag=bar` or even `GET /#?tag=#token=foo`, `req.url` is always `/`. Is this a limitation of Iron?

**Comment by s-panferov** [comment]
Fragment identifiers are not sent to the server.

**Comment by hjfitz** [comment]
Figured this out after posting - should have updated the issue :+1:
